name: RFT Java CI

on: [push]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Compile with Maven
        uses: dawidd6/action-maven@v2
        with:
          args: ./RFT_Neptun/pom.xml compile

      - name: Test with Maven
        uses: dawidd6/action-maven@v2
        with:
          args: ./RFT_Neptun/pom.xml test

      - name: Coverage with JaCoCo
        if: always()
        uses: dawidd6/action-maven@v2
        with:
          args: ./RFT_Neptun/pom.xml jacoco:report

      - name: Publish coverage report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: neptun-coverage
          path: ./RFT_Neptun/target/site/jacoco